FROM adoptopenjdk/openjdk11:alpine-jre
VOLUME /tmp
COPY app-dev1/target/*.jar app.jar
RUN mkdir logs && touch /logs/spring-boot-logger.log
RUN ln -sf /dev/stdout /logs/spring-boot-logger.log
ENTRYPOINT exec java -jar /app.jar -DconfDir=/etc/config