apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
      annotations:
        configHash: "1" # real config hash or commit id https://blog.questionable.services/article/kubernetes-deployments-configmap-change/
    spec:
      containers:
        - name: web-uat15
          image: lemartis/docker-spring-test
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: config-uat15