apiVersion: v1
kind: Pod
metadata:
  name: app-dev1-pod
  labels:
    app: app-dev1
spec:
  containers:
    - name: app-dev1-cnt
      image: ikozar22/docker-spring-test:dev1-tag
      volumeMounts:
          - name: app-dev1-vol
            mountPath: /etc/config
  volumes:
    - name: app-dev1-vol
      configMap:
        name: config-dev1
---
apiVersion: v1
kind: Service
metadata:
  name: app-dev1-srv
spec:
  type: ClusterIP
  ports:
    - name: app-dev1-port
      port: 8080
      targetPort: 8080
  selector:
    app: bright-etl-uat15
---
apiVersion: v1
kind: Service
metadata:
  name: bright-etl-uat16-srv
spec:
#  type: ClusterIP
  type: NodePort
  ports:
    - name: bright-etl-uat16-port
      port: 8080
      targetPort: 8080
      nodePort: 30002
  selector:
    app: bright-etl-uat16
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bright-ingress
spec:
#  backend:
#    serviceName: bright-ingress-srv
#    servicePort: 8080
  rules:
    - host: etl.uat15.bnp.com
      http:
        paths:
          - backend:
              serviceName: bright-etl-uat15-srv
              servicePort: 8080
    - host: etl.uat16.bnp.com
      http:
        paths:
          - backend:
              serviceName: bright-etl-uat16-srv
              servicePort: 8080
